### ISSUE TITLE
Subset of wires from a sketch

### ISSUE THREAD

**Issue by macdroid53** [mwganson/wirefilter#2]
Probably me not understanding what is supposed to happen.

In the attached file, I select Sketch002 Edge3 and Edge 2.

The resultant WireFilter shows them as the source, but when selected it shows all the edges from Sketch002 (and if extruded (in Part) it extrudes the the shape of Sketch002.
[SplineCut-3.ZIP](https://github.com/mwganson/wirefilter/files/7777073/SplineCut-3.ZIP)
 (github barfed on an FCStd file...)

**Comment by mwganson** [comment]
From the readme:

>  If one or more edges are selected, then the wires that contain those edges will be filtered for use.

This makes it easy to select a wire that has many edges because you only need to select one or more edges from that wire.

There is a way to filter edges of the wire filter.  Make sure the sketch is invisible.  Select the desired edges of the wirefilter object, set the Select Edges property to True.  This populates the Selected Edges property with the names of those edges.  Then toggle Use Selected to True.

![Snip macro screenshot-f3bbd1](https://user-images.githubusercontent.com/39143564/147412794-8813ebd0-399d-40ef-b799-5e4685e1277f.png)

In a workbench you would have toolbar icons, but since this is a macro I had to make do with using boolean properties for command triggers.  You toggle to true to execute the command and the property sets itself back to false for the next time it gets used.

We can also (sometimes) create a new wire by using edges from 2 or more wires.  Consider this sketch:

![Snip macro screenshot-b83d73](https://user-images.githubusercontent.com/39143564/147412909-271a3c5a-9811-4aa3-878c-baa9ec567af3.png)
![Snip macro screenshot-c8407d](https://user-images.githubusercontent.com/39143564/147412936-a080ac24-39d9-4e80-ad8a-50f72fd5ad13.png)

![Snip macro screenshot-8e2f7c](https://user-images.githubusercontent.com/39143564/147412966-f8b4d4e7-e4f8-4905-8d82-19299920ccf0.png)

**Comment by macdroid53** [comment]
Aha...yes, "me no lo comprende" the bit about "There is a way to filter edges of the wire filter".

That clears it up, thanks.
